allowBuilds:
  workerd: true
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@oxfmt/binding-android-arm-eabi@0.70.0'
  - '@oxfmt/binding-android-arm64@0.70.0'
  - '@oxfmt/binding-darwin-arm64@0.70.0'
  - '@oxfmt/binding-darwin-x64@0.70.0'
  - '@oxfmt/binding-freebsd-x64@0.70.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.70.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.70.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.70.0'
  - '@oxfmt/binding-linux-arm64-musl@0.70.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.70.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.70.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.70.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.70.0'
  - '@oxfmt/binding-linux-x64-gnu@0.70.0'
  - '@oxfmt/binding-linux-x64-musl@0.70.0'
  - '@oxfmt/binding-openharmony-arm64@0.70.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.70.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.70.0'
  - '@oxfmt/binding-win32-x64-msvc@0.70.0'
  - '@oxlint/binding-android-arm-eabi@1.85.0'
  - '@oxlint/binding-android-arm64@1.85.0'
  - '@oxlint/binding-darwin-arm64@1.85.0'
  - '@oxlint/binding-darwin-x64@1.85.0'
  - '@oxlint/binding-freebsd-x64@1.85.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.85.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.85.0'
  - '@oxlint/binding-linux-arm64-gnu@1.85.0'
  - '@oxlint/binding-linux-arm64-musl@1.85.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.85.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.85.0'
  - '@oxlint/binding-linux-riscv64-musl@1.85.0'
  - '@oxlint/binding-linux-s390x-gnu@1.85.0'
  - '@oxlint/binding-linux-x64-gnu@1.85.0'
  - '@oxlint/binding-linux-x64-musl@1.85.0'
  - '@oxlint/binding-openharmony-arm64@1.85.0'
  - '@oxlint/binding-win32-arm64-msvc@1.85.0'
  - '@oxlint/binding-win32-ia32-msvc@1.85.0'
  - '@oxlint/binding-win32-x64-msvc@1.85.0'
  - oxfmt@0.70.0
  - oxlint@1.85.0
  - '@cloudflare/unenv-preset@2.16.2'
  - '@cloudflare/vite-plugin@1.57.1'
  - '@cloudflare/workerd-darwin-64@1.20260921.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260921.1'
  - '@cloudflare/workerd-linux-64@1.20260921.1'
  - '@cloudflare/workerd-linux-arm64@1.20260921.1'
  - '@cloudflare/workerd-windows-64@1.20260921.1'
  - miniflare@5.20260921.0-alpha
  - workerd@1.20260921.1
  - wrangler@4.136.1
